services:
  frontend:
    build:
      context: .
      target: dev
      dockerfile: ./frontend/Dockerfile
    tty: true
    volumes:
      # `.git` をコンテナ内で参照できるようにするため、
      # `/workspace` 直下にリポジトリのルートディレクトリごとマウントする
      - type: bind
        source: .
        target: /workspace
        consistency: cached
      # 名前付きボリュームに隠す
      - type: volume
        source: front-node-modules
        target: /workspace/frontend/node_modules
      - type: volume
        source: front-next
        target: /workspace/frontend/.next
    ports:
      - 3000:3000
  mock:
    build:
      context: .
      dockerfile: ./frontend/mock/Dockerfile
    volumes:
      - type: bind
        source: ./frontend/mock
        target: /workspace
        consistency: cached
    ports:
      - 3001:3000
  rest:
    build:
      context: .
      target: dev
      dockerfile: ./backend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: .
        target: /workspace
        consistency: cached
    ports:
      - 18080:8080
volumes:
  front-node-modules:
  front-next: