version: "3.9"

services:
  frontend:
    container_name: foderee-frontend
    hostname: foderee-frontend
    build:
      context: .
      target: dev
      dockerfile: ./frontend/Dockerfile
    tty: true
    volumes:
      # `.git` をコンテナ内で参照できるようにするため、
      # `/workspace` 直下にリポジトリのルートディレクトリごとマウントする
      - .:/workspace:cached
    ports:
      - 3000:3000
