name: Test for Go

on:
  push:
    branches:
      - "main"
    paths:
      - "**/*.go"
      - .github/workflows/test-go.yml
  pull_request:
    paths:
      - "**/*.go"
      - .github/workflows/test-go.yml

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./backend/go.mod

      - name: Run tests with coverage report output
        run: go test ./... -coverprofile=coverage.out

      - name: Create report
        uses: k1LoW/octocov-action@v0